{{ if .Values.metrics.serviceMonitor.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vector.fullname" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vector.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
{{- end }}
